name: ${artifactId}
main: ${groupId}.${artifactId}
author: Maxim Varentsov <admin@gtncraft.ru>
version: ${version}

permissions:
    spawn.set:
        default: op
    spawn.use:
        default: true

commands:
  setspawn:
     description: Установка точки спавна в мире.
     permission: spawn.set
  spawn:
     description: Телепортирование на точку спавна.
     permission: spawn.use